on:
  workflow_dispatch:
    inputs:
      command:
        type: choice
        options:
          - release-pr
          - github-release
        default: release-pr

permissions:
  contents: write
  pull-requests: write

name: manual release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          command: ${{inputs.command}}
          release-type: node
          package-name: my-package
          default-branch: main
