on:
  # when we merge a PR to next, create a draft release PR to main
  push:
    branches:
      - next

permissions:
  contents: write
  pull-requests: write

name: prerelease-please

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: my-package-prerelease
          default-branch: next
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: my-package
          default-branch: main
