on:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: prerelease-please

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # - name: Check source branch
      #   run: exit 1
      #   if: github.event_name == 'pull_request' && github.event.pull_request.head.ref != 'main'
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: my-package
          # the current pull request branch:
          default-branch: ${{ github.event.pull_request.head.ref }}
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: install release-please
        run: npm install -g release-please
      - run: release-please release-pr --trace --dry-run --release-type=node --repo-url=${{github.repository_owner}}/${{github.repository.name}} --token=${{secrets.GITHUB_TOKEN}} --target-branch=${{github.event.pull_request.head.ref}}
