on:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: prerelease-please

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # - name: Check source branch
      #   run: exit 1
      #   if: github.event_name == 'pull_request' && github.event.pull_request.head.ref != 'main'
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: my-package
          # the current pull request branch:
          default-branch: ${{ github.event.pull_request.head.ref }}
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: install release-please
        run: npm install -g release-please
        # add the output to a github env var

        # echo 'DIFF<<EOF' >> $GITHUB_ENV
        # echo "${DIFF}" >> $GITHUB_ENV
        # echo 'EOF' >> $GITHUB_ENV
      - run: |
          echo 'RELEASE_PLEASE_OUTPUT<<EOF' >> $GITHUB_ENV
          echo $(release-please release-pr --trace --dry-run --release-type=node --repo-url=${{github.repository}} --token=${{secrets.GITHUB_TOKEN}} --target-branch=${{github.event.pull_request.head.ref}} | awk '/Index\:/{flag=1} flag') >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - run: echo $RELEASE_PLEASE_OUTPUT
      - name: comment the output on the pr
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: preview
          message: |
            ```diff
            $RELEASE_PLEASE_OUTPUT
            ```
